import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import WagmiConnect from '../components/connect/wagmiconnect';
import { WagmiConfig, createClient } from 'wagmi'
import { getDefaultProvider } from 'ethers'

const inter = Inter({ subsets: ['latin'] })

const client = createClient({
  autoConnect: true,
  provider: getDefaultProvider(),
});

export default function Home() {

  return (
    <>
      <Head>
        <title>WorldHomes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <WagmiConfig client={client}>
          <WagmiConnect></WagmiConnect>
        </WagmiConfig>
      </main>
    </>
  )
}
